config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => "homes#about", as: 'about'
  resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :about]
  resources :users, only: [:show, :edit, :index, :update]
  patch 'books/:id' => 'books#update', as: 'update_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, length: {maximum: 200}, presence: true
  
end

app/models/post_book.rb
class PostBook < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image

  validates :name, length: {minimum: 2, maximum: 20}, presence: true, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resourse)
    user_path(resourse)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @post_book = PostBook.new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id]) 
    unless @book.user.id == current_user.id   
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books.all
  end

  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    book.save
    redirect_to books_path
  end

  def index
    @user = current_user
    @users = User.all
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def new
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_left.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
  
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="btn-wrapper mx-auto">
  <div class="row">
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block edit-user" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
</div>

<h1>New book</h1>
<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <button class="btn btn-success">
    Create Book
  </button>

<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <h1>Editing Book</h1>

      <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

        <div class="field">
          <p>Title</p>
          <%= f.text_field :title, class:"form-control" %>
        </div>

        <div class="field">
          <p>Opinion</p>
          <%= f.text_area :body, class:"form-control mb-3" %>
        </div>
         
        <div class="field">
          <button class="btn btn-success">
            Update Book
          </button>
        </div>
          
      <% end %>

      <%= link_to book_path do %>Show<% end %> | <%= link_to books_path do %>Back<% end %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'left', user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <th>
                  <%= link_to user_path(book.user) do %>
                    <%= image_tag book.user.get_profile_image(100,100) %>
                  <% end %>
                </th>
                <th>
                  <%=link_to book_path(book.id) do %>
                    <span><%= book.title %></span>
                  <% end %>
                </th>
                <th>
                  <span><%= book. body %></span>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'left', user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= image_tag @user.get_profile_image(100,100) %>
                </br>
                <%= link_to user_path(@user.id) do %> 
                  <% @user.name %>
                <% end %>
              </td>
              <td>
                <%= @book.title %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <% if @user == current_user %>
                <td>
                  <%= link_to edit_book_path(@book.id), class:"btn btn-sm btn-success" do %>
                    Edit
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path, class:"btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" do %>
                    Destroy
                  <% end %>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!!</h1>
      <P>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>  
      <p>you can share and exchange your opinions , inpressions , and emotions about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign-in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/6ab161fb74.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <% if user_signed_in? %> 
            <a class="navbar-brand" href="/">
              <span>Bookers</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" arai-expanded="false" arai-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li>
                  <%= link_to user_path(current_user), class:"nav-link text-light" do %>
                    <i class="fa-solid fa-home"></i>
                      Home
                      <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fa-solid fa-users"></i>
                      Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-light" do %>
                    <i class="fa-solid fa-book-open"></i>
                      Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fa-solid fa-sign-out-alt"></i>
                      Log out
                  <% end %>
                </li>
              </ul>
            </div>
          <% else %>
          <a class="navbar-brand" href="/">
              <span>Bookers</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" arai-expanded="false" arai-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li>
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fa-solid fa-home"></i>
                      Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "nav-link text-light" do %>
                    <i class="fa-solid fa-link"></i>
                      About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do%>
                    <i class="fa-solid fa-user-plus"></i>
                      Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do%>
                  <i class="fa-solid fa-sign-in-alt"></i>
                    Log in
                  <% end %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </nav>
    </header>

    <main>
      <div>
        <%= flash[:notice] %>
      </div>
      <%= yield %> 
    </main>
    
    <footer>
      <div class="container mt-5>
        <div class="row">
          <div class="mx-auto">
            <p class="text-center">CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_left.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
  
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="btn-wrapper mx-auto">
  <div class="row">
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block edit-user" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
</div>

<h1>New book</h1>
<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <button class="btn btn-success">
    Create Book
  </button>

<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>User Info</h1>

<%= form_with model: @user, url: user_path(@user.id) do |f| %>

  <p>Name</p>
  <%= f.text_field :name %>

  <p>Image</p>
  <%= f.file_field :profile_image, accept: "image/*" %>

  <p>Introduction</p>
  <%= f.text_field :introduction %>
      
  <%= f.submit 'Update User' %>
      
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'left', user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <th>
                  <%= image_tag user.get_profile_image(100,100) %>
                </th>
                <th>
                  <span><%= user.name %></span>
                </th>
                <th>
                  <%=link_to user_path(user.id) do %>
                    Show
                  <% end %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'left', user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <th>
                  <%= link_to user_path(book.user) do %>
                    <%= image_tag @user.get_profile_image(100,100) %>
                  <% end %>
                </th>
                <th>
                  <%=link_to book_path(book.id) do %>
                    <span><%= book.title %></span>
                  <% end %>
                </th>
                <th>
                  <span><%= book. body %></span>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>